name: Update README Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=radical
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&theme=radical
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate cdat-pattern pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=dar-kow&repo=cdat-pattern&theme=radical
          path: profile/pin-cdat-pattern.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate demo-bi pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=dar-kow&repo=demo-bi&theme=radical
          path: profile/pin-demo-bi.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate M-A-F pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=dar-kow&repo=M-A-F&theme=radical
          path: profile/pin-maf.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Portfolio pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=dar-kow&repo=Portfolio&theme=radical
          path: profile/pin-portfolio.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate maf-e2e-pw pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=dar-kow&repo=maf-e2e-pw&theme=radical
          path: profile/pin-maf-e2e-pw.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate k6-dashboard pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=dar-kow&repo=k6-dashboard&theme=radical
          path: profile/pin-k6-dashboard.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "chore: update README stats cards" || exit 0
          git push
